import Head from "next/head";
import Image from "next/image";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faMagnifyingGlass, faPlus } from "@fortawesome/free-solid-svg-icons";
import { useRouter } from "next/router";
import { v4 as uuid } from "uuid";
export default function Home() {
  const router = useRouter();
  function createRoom() {
    const id = uuid();
    router.push(`room/${id}`);
  }
  function createRoomWrtc() {
    const id = uuid();
    router.push(`wrtc/${id}`);
  }
  function createRoomSoup() {
    const id = uuid();
    router.push(`soup/${id}`);
  }

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="container" dir="rtl">
        <div className="row mt-5 justify-content-center">
          <div className="col-12 col-sm-11 col-md-8 col-lg-6">
            <div className="card">
              <div className="card-body px-4">
                <div className="row">
                  <button
                    className="btn btn-primary"
                    style={{ fontSize: "22px" }}
                    onClick={() => createRoom()}
                  >
                    <FontAwesomeIcon
                      icon={faPlus}
                      style={{ paddingLeft: "5px" }}
                    />
                    ایجاد اتاق جدید
                  </button>
                </div>
                <div className="row mt-2">
                  <button
                    className="btn btn-success"
                    style={{ fontSize: "22px" }}
                    onClick={() => createRoomWrtc()}
                  >
                    <FontAwesomeIcon
                      icon={faPlus}
                      style={{ paddingLeft: "5px" }}
                    />
                    ایجاد اتاق WRTC
                  </button>
                </div>
                <div className="row mt-2">
                  <button
                    className="btn btn-success"
                    style={{ fontSize: "22px" }}
                    onClick={() => createRoomSoup()}
                  >
                    <FontAwesomeIcon
                      icon={faPlus}
                      style={{ paddingLeft: "5px" }}
                    />
                    ایجاد اتاق Soup
                  </button>
                </div>
                <div className="row mt-2">
                  <button
                    className="btn btn-secondary"
                    style={{ fontSize: "22px" }}
                  >
                    <FontAwesomeIcon
                      icon={faMagnifyingGlass}
                      style={{ paddingLeft: "5px" }}
                    />
                    ورود به اتاق
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
